//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicRolodex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public System.Guid Id { get; set; }
        public System.Guid User_Id { get; set; }
        public int contactType_Id { get; set; }
        public System.Guid Contact_Id { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual User User { get; set; }
    }
}
